name: Weekly Cleanup

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly at midnight Sunday
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Purge build artifacts
        run: |
          rm -rf android/app/build/
          rm -rf dist/
          rm -rf node_modules/
          echo "Cleanup complete."
