name: Secret Scanning

on:
  push:
    branches: [ main, dev, staged ]
  pull_request:
    branches: [ main, dev, staged ]

jobs:
  gitguardian:
    name: GitGuardian Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@53910b10ce6646fb7c6e353f55f26ed96d0cff1b # v1.32.0
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        if: env.GITGUARDIAN_API_KEY != ''
